version: "3"

services:
  namenode:
    build:
      context: docker
      dockerfile: namenode/Dockerfile
    image: hadoop-namenode
    container_name: hive_docker_namenode
    ports:
      - "8020:8020"
    environment:
      - CLUSTER_NAME=test
    env_file:
      - docker/hadoop.env

  datanode:
    build:
      context: docker
      dockerfile: datanode/Dockerfile
    image: hadoop-datanode
    container_name: hive_docker_datanode
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - docker/hadoop.env

  hive-server:
    build:
      context: docker
      dockerfile: hive/Dockerfile
    image: hive:latest
    container_name: hive_server
    env_file:
      - docker/hadoop.env
    volumes:
      - parquet_data:/parquet_data
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    build:
      context: docker
      dockerfile: hive/Dockerfile
    image: hive
    env_file:
      - docker/hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"

  hive-metastore-postgresql:
    build:
      context: docker
      dockerfile: postgres_metastore/Dockerfile
    image: hive-metastore-postgresql

  test-executor:
    build:
      context: docker
      dockerfile: test_executor/Dockerfile
    image: test-executor
    environment:
      SERVICE_PRECONDITION: "hive-server:10000"
      DEBUG: "${DEBUG}"
    volumes:
      - parquet_data:/parquet_data

volumes:
  parquet_data:
